name: My Simple Docker App

on:
  push:
    branches:
      - main
jobs:
  echo_name:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Name
        run: echo "Hello, Sepehr!"
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Date
        run: date
